# Generated by Django 5.2.8 on 2025-11-15 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('movie', 'Filme'), ('tv', 'Série')], max_length=10)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(help_text='Por que você gostaria que este conteúdo fosse adicionado?')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('added', 'Adicionada')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notas do administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(blank=True, max_length=200)),
                ('overview', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=200)),
                ('backdrop_path', models.CharField(blank=True, max_length=200)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('media_type', models.CharField(choices=[('movie', 'Filme'), ('tv', 'Série')], max_length=10)),
                ('runtime', models.IntegerField(blank=True, help_text='Duração em minutos', null=True)),
                ('vote_average', models.FloatField(default=0.0)),
                ('vote_count', models.IntegerField(default=0)),
                ('popularity', models.FloatField(default=0.0)),
                ('original_language', models.CharField(blank=True, max_length=10)),
                ('number_of_seasons', models.IntegerField(blank=True, null=True)),
                ('number_of_episodes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, to='catalog.genre')),
            ],
            options={
                'ordering': ['-popularity', '-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='catalog.media')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('profile_path', models.CharField(blank=True, max_length=200)),
                ('tmdb_person_id', models.IntegerField(blank=True, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='catalog.media')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('character', models.CharField(blank=True, max_length=200)),
                ('profile_path', models.CharField(blank=True, max_length=200)),
                ('tmdb_person_id', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_members', to='catalog.media')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type'], name='catalog_med_media_t_45733f_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['tmdb_id'], name='catalog_med_tmdb_id_26f24f_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['-popularity'], name='catalog_med_popular_d2b6a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'media')},
        ),
    ]
