# Generated by Django 5.2.8 on 2025-11-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='character',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cast',
            name='profile_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='profile_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
